# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/kbookmarks': '@stable'
    'frameworks/kcodecs': '@stable'
    'frameworks/kcompletion': '@stable'
    'frameworks/kconfig': '@stable'
    'frameworks/kconfigwidgets': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/kdbusaddons': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kitemviews': '@stable'
    'frameworks/kjobwidgets': '@stable'
    'frameworks/knotifications': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kservice': '@stable'
    'frameworks/ktextwidgets': '@stable'
    'frameworks/kwallet': '@stable'
    'frameworks/kwidgetsaddons': '@stable'
    'frameworks/kxmlgui': '@stable'
