# Set the install prefix
IF(NOT DEFINED CMAKE_INSTALL_PREFIX)
      SET(CMAKE_INSTALL_PREFIX "/usr")
      ENDIF(NOT DEFINED CMAKE_INSTALL_PREFIX)
      STRING(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

IF($ENV{DESTDIR} MATCHES ".+")
    SET(DESTDIR $ENV{DESTDIR})
ELSE($ENV{DESTDIR} MATCHES ".+")
    SET(DESTDIR "")
ENDIF($ENV{DESTDIR} MATCHES ".+")

EXECUTE_PROCESS(
    COMMAND ln "-s" "../common" "common"
    WORKING_DIRECTORY "${DESTDIR}/${CMAKE_INSTALL_PREFIX}/share/doc/HTML/en/kdesvn"
    )

