IF($ENV{DESTDIR} MATCHES ".+")
    SET(DESTDIR $ENV{DESTDIR})
ELSE($ENV{DESTDIR} MATCHES ".+")
    SET(DESTDIR "")
ENDIF($ENV{DESTDIR} MATCHES ".+")

SET(COMMONLINK "${DESTDIR}${CMAKE_INSTALL_PREFIX}/share/doc/HTML/en/kdesvn/common")

MESSAGE(STATUS "Generating ${COMMONLINK}")

EXECUTE_PROCESS(
    COMMAND "rm" "-f" "common"
    COMMAND ln "-s" "../common" "common"
    WORKING_DIRECTORY "${DESTDIR}/${CMAKE_INSTALL_PREFIX}/share/doc/HTML/en/kdesvn"
    )

SET(CMAKE_INSTALL_MANIFEST_FILES ${CMAKE_INSTALL_MANIFEST_FILES} "${CMAKE_INSTALL_PREFIX}/share/doc/HTML/en/kdesvn/common")

