SET(SUBVERSIONFOUND)

FIND_PATH(SUBVERSION_INCLUDE_DIR svn_client.h
 /usr/include/subversion-1
 /usr/local/include/subversion-1
)

FIND_LIBRARY(SUBVERSION_CLIENTLIB svn_client-1
 /usr/lib
 /usr/local/lib
)

FIND_LIBRARY(SUBVERSION_REPOSITORYLIB svn_repos-1
 /usr/lib
 /usr/local/lib
)

FIND_LIBRARY(SUBVERSION_WCLIB svn_wc-1
 /usr/lib
 /usr/local/lib
)

FIND_LIBRARY(SUBVERSION_FSLIB svn_fs-1
 /usr/lib
 /usr/local/lib
)

FIND_LIBRARY(SUBVERSION_SUBRLIB svn_subr-1
 /usr/lib
 /usr/local/lib
)

FIND_LIBRARY(SUBVERSION_RALIB svn_ra-1
 /usr/lib
 /usr/local/lib
)

FIND_PROGRAM(APR_CONFIG NAMES apr-config apr-1-config
 PATHS
 /usr/local/apr/bin
)

FIND_PROGRAM(APU_CONFIG NAMES apu-config apu-1-config
 PATHS
 /usr/local/apr/bin
)

SET(SUBVESION_ALL_LIBS)

IF(NOT SUBVERSION_INCLUDE_DIR)
  MESSAGE(SEND_ERROR "No subversion includes found!")
ELSE(NOT SUBVERSION_INCLUDE_DIR)
  MESSAGE(STATUS "Found subversion include: ${SUBVERSION_INCLUDE_DIR}")
ENDIF(NOT SUBVERSION_INCLUDE_DIR)

if (NOT SUBVERSION_CLIENTLIB)
 MESSAGE(SEND_ERROR "No subversion client libs found!")
ELSE (NOT SUBVERSION_CLIENTLIB)
 MESSAGE(STATUS "Found subversion client lib: ${SUBVERSION_CLIENTLIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_CLIENTLIB})
endif(NOT SUBVERSION_CLIENTLIB)

if (NOT SUBVERSION_REPOSITORYLIB)
 MESSAGE(SEND_ERROR "No subversion repository lib found!")
ELSE (NOT SUBVERSION_REPOSITORYLIB)
 MESSAGE(STATUS "Found subversion repository lib: ${SUBVERSION_REPOSITORYLIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_REPOSITORYLIB})
endif(NOT SUBVERSION_REPOSITORYLIB)

if (NOT SUBVERSION_FSLIB)
 MESSAGE(SEND_ERROR "No subversion fs lib found!")
ELSE (NOT SUBVERSION_FSLIB)
 MESSAGE(STATUS "Found subversion fs lib: ${SUBVERSION_FSLIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_FSLIB})
endif(NOT SUBVERSION_FSLIB)

if (NOT SUBVERSION_SUBRLIB)
 MESSAGE(SEND_ERROR "No subversion subr lib found!")
ELSE (NOT SUBVERSION_SUBRLIB)
 MESSAGE(STATUS "Found subversion subr lib: ${SUBVERSION_SUBRLIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_SUBRLIB})
endif(NOT SUBVERSION_SUBRLIB)

if (NOT SUBVERSION_WCLIB)
 MESSAGE(SEND_ERROR "No subversion wc lib found!")
ELSE (NOT SUBVERSION_WCLIB)
 MESSAGE(STATUS "Found subversion wc lib: ${SUBVERSION_WCLIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_WCLIB})
endif(NOT SUBVERSION_WCLIB)

if (NOT SUBVERSION_RALIB)
 MESSAGE(SEND_ERROR "No subversion ra lib found!")
ELSE (NOT SUBVERSION_RALIB)
 MESSAGE(STATUS "Found subversion ra lib: ${SUBVERSION_RALIB}")
 SET(SUBVESION_ALL_LIBS ${SUBVESION_ALL_LIBS} ${SUBVERSION_RALIB})
endif(NOT SUBVERSION_RALIB)

if(NOT APR_CONFIG)
 MESSAGE(SEND_ERROR "Error: no apr-config found")
endif(NOT APR_CONFIG)

if(NOT APU_CONFIG)
 MESSAGE(SEND_ERROR "Error: no apu-config found")
endif(NOT APU_CONFIG)

EXEC_PROGRAM(${APR_CONFIG} ARGS "--includedir" OUTPUT_VARIABLE APR_INCLUDE_DIR)
EXEC_PROGRAM(${APU_CONFIG} ARGS "--includedir" OUTPUT_VARIABLE APU_INCLUDE_DIR)

EXEC_PROGRAM(${APR_CONFIG} ARGS "--cppflags" OUTPUT_VARIABLE APR_CPP_FLAGS)
EXEC_PROGRAM(${APU_CONFIG} ARGS "--cppflags" OUTPUT_VARIABLE APU_CPP_FLAGS)

EXEC_PROGRAM(${APR_CONFIG} ARGS "--ldflags --libs --link-ld" OUTPUT_VARIABLE APR_EXTRA_LIBFLAGS)
EXEC_PROGRAM(${APU_CONFIG} ARGS "--ldflags --libs --link-ld" OUTPUT_VARIABLE APU_EXTRA_LIBFLAGS)

SET(SUBVERSIONFOUND true)

